import { ChangeDetectionStrategy, Component, type OnInit } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CartService } from '../../services/cart.service';
import { Product, ProductService } from '../../services/product.service';
import { ToastService } from '../../services/toast.service';
import { WishlistService } from '../../services/wishlist.service';

@Component({ selector:'app-product-detail', standalone:true, imports:[CommonModule, CurrencyPipe, RouterLink], changeDetection:ChangeDetectionStrategy.OnPush, template:`<main class="min-h-screen bg-slate-50 px-4 pb-16 pt-28"><div *ngIf="product as item" class="mx-auto max-w-6xl"><a routerLink="/products" class="text-sm font-semibold text-sky-700">← All products</a><div class="mt-6 grid gap-10 rounded-3xl bg-white p-5 shadow-sm sm:p-8 lg:grid-cols-2"><section><div class="overflow-hidden rounded-2xl bg-slate-100"><img [src]="activeImage" [alt]="item.name" class="aspect-square w-full object-cover transition hover:scale-125"></div><div class="mt-3 flex gap-3 overflow-auto"><button *ngFor="let image of item.images" (click)="activeImage=image.url" class="h-16 w-16 shrink-0 overflow-hidden rounded-lg border-2" [class.border-sky-500]="image.url===activeImage"><img [src]="image.url" [alt]="image.alt || item.name" class="h-full w-full object-cover"></button></div></section><section><p class="text-sm font-bold uppercase tracking-widest text-sky-600">{{item.category.name}}</p><h1 class="mt-2 text-4xl font-black text-slate-900">{{item.name}}</h1><p class="mt-4 text-3xl font-black text-slate-900">{{item.price|currency}}</p><p class="mt-5 leading-7 text-slate-600">{{item.description || 'Product details are available from the catalogue.'}}</p><p class="mt-4 font-semibold" [class.text-emerald-600]="item.stock>0" [class.text-red-600]="item.stock===0">{{item.stock>0 ? item.stock+' available' : 'Out of stock'}}</p><div class="mt-7 flex gap-3"><button (click)="add(item)" [disabled]="item.stock===0" class="flex-1 rounded-xl bg-slate-900 px-5 py-3 font-bold text-white disabled:opacity-50">Add to cart</button><button (click)="wish(item.id)" class="rounded-xl border border-slate-300 px-5 font-bold text-slate-700" aria-label="Add to wishlist">♡</button></div></section></div><section class="mt-10"><h2 class="text-2xl font-black text-slate-900">Customer reviews</h2><p *ngIf="!item.reviews?.length" class="mt-3 text-slate-500">No reviews yet.</p><article *ngFor="let review of item.reviews" class="mt-4 rounded-2xl bg-white p-5 shadow-sm"><p class="font-bold">{{review.rating}} / 5</p><p class="mt-2 text-slate-600">{{review.comment}}</p></article></section></div><p *ngIf="!product" class="py-32 text-center text-slate-500">Loading product…</p></main>`})
export class ProductDetailComponent implements OnInit { product?:Product; activeImage='assets/images/placeholder.jpg'; constructor(private route:ActivatedRoute,private api:ProductService,private cart:CartService,private wishlist:WishlistService,private toast:ToastService){} ngOnInit(){const id=this.route.snapshot.paramMap.get('id');if(id)this.api.getProductById(id).subscribe({next:r=>{this.product=r.data;this.activeImage=r.data.images[0]?.url||this.activeImage},error:()=>this.toast.error('Product unavailable','This product could not be found.')});}add(product:Product){this.cart.addToCart(product.id).subscribe({next:()=>{this.cart.openCart();this.toast.success('Added to cart',product.name)},error:e=>this.toast.error('Unable to add to cart',e.error?.message||'Please sign in and try again.')});}wish(id:string){this.wishlist.addToWishlist(id).subscribe({next:()=>this.toast.success('Saved to wishlist','Product added to your wishlist.'),error:e=>this.toast.error('Unable to save',e.error?.message||'Please sign in and try again.')});}}
