// Ambient declaration for the `process.env.NG_APP_*` variables injected at
// build/serve time by @ngx-env/builder (see angular.json's `build`/`serve`
// builders). Normally generated by `ng add @ngx-env/builder`; created here
// by hand since the builder was wired in manually.
declare const process: {
  env: {
    NG_APP_ENV: string;
    NG_APP_API_URL: string;
    [key: string]: string | undefined;
  };
};
